sudo: false
language: node_js
branches:
  only:
  - master
cache:
  directories:
    - "node_modules"
    - "packages/cli/lib"
    - "packages/code-dependency/lib"
    - "packages/converter/lib"
    - "packages/extract/lib"
    - "packages/interfaces/lib"
    - "packages/resolver/lib"
    - "packages/view/lib"
    - "packages/code-dependency/buildcache"
    - "packages/converter/buildcache"
    - "packages/extract/buildcache"
    - "packages/interfaces/buildcache"
    - "packages/resolver/buildcache"
    - "packages/view/buildcache"
stages:
- name: lint & build & test
  if: branch = master AND type = pull_request
- name: deploy
  if: branch = master AND type = push
jobs:
  include:
  - stage: lint & build & test
    script:
    - yarn run setup:ci
    - yarn run lint
    - yarn run build:lib
    - yarn run build
    - yarn run test:ci
    - yarn run setup:ci
    node_js:
    - '11'
  - stage: deploy
    script:
    - yarn run clean
    - yarn run build:lib
    - yarn build
    - echo '//registry.npmjs.org/:_authToken="${NPM_TOKEN}"' >> .npmrc
    # - npm publish
    # - cp .npmrc.template .npmrc
    node_js:
    - '11'
