sudo: false
language: node_js
branches:
  only:
  - master
cache:
  directories:
    - "node_modules"
    - "packages/cli/lib"
    - "packages/code-dependency/lib"
    - "packages/converter/lib"
    - "packages/extract/lib"
    - "packages/interfaces/lib"
    - "packages/resolver/lib"
    - "packages/view/lib"
stages:
- name: lint
  if: branch = master AND type = pull_request
- name: compile
  if: branch = master AND type = pull_request
- name: test
  if: branch = master AND type = pull_request
- name: deploy
  if: branch = master AND type = push
jobs:
  include:
  - stage: lint
    script: yarn run lint
    node_js:
    - '11'
  - stage: compile
    script: yarn run build:lib
    node_js:
    - '11'
  - stage: test
    script:
    - yarn run build:lib
    - yarn run test:ci
    node_js:
    - '11'
  - stage: deploy
    script:
    - yarn install
    - yarn build
    - echo '//registry.npmjs.org/:_authToken="${NPM_TOKEN}"' >> .npmrc
    # - npm publish
    # - cp .npmrc.template .npmrc
    node_js:
    - '11'
